/// Flutter icons SpendSafeIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SpendSafeIcon
///      fonts:
///       - asset: fonts/SpendSafeIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SpendSafeIcon {
  SpendSafeIcon._();

  static const _kFontFam = 'SpendSafeIcon';
  static const String? _kFontPkg = null;

  static const IconData expande_more_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData new_user_icon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_icon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_icon = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData salary_icon = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData saving_icon = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search__icon = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
